import * as path from 'path';
import * as fs from 'fs';
import { execSync } from 'child_process';
import Module from 'module';

// Polyfill Node module resolution to automatically fall back from .js to .ts (for ESM relative imports inside ts-node)
const origResolve = (Module as any)._resolveFilename;
(Module as any)._resolveFilename = function (request: string, parent: any, isMain: boolean, options: any) {
    if (request === '@sheep-family/types') {
        request = path.join(__dirname, '../modules/SheepComb/packages/types/src/index.ts');
    }
    try {
        return origResolve.call(this, request, parent, isMain, options);
    } catch (err: any) {
        if (request.endsWith('.js')) {
            const tsRequest = request.slice(0, -3) + '.ts';
            try {
                return origResolve.call(this, tsRequest, parent, isMain, options);
            } catch (e) {
                // ignore
            }
        }
        throw err;
    }
};

// Bypass ERR_REQUIRE_ESM for workspace packages during ts-node script execution
const origReadPkg = (Module as any)._readPackage;
if (origReadPkg) {
    (Module as any)._readPackage = function (...args: any[]) {
        const pkg = origReadPkg.apply(this, args);
        if (pkg && pkg.type === 'module') {
            return { ...pkg, type: 'commonjs' };
        }
        return pkg;
    };
}

import { ShWvData } from '../src/services/core/ShWvData';

function resolveTikalPath(rootDir: string): string {
    const defaultOkapiTikal = path.join(rootDir, 'okapi', 'tikal.bat');
    if (fs.existsSync(defaultOkapiTikal)) {
        return defaultOkapiTikal;
    }
    const siblingOkapiTikal = path.join(rootDir, '..', 'okapi', 'tikal.bat');
    if (fs.existsSync(siblingOkapiTikal)) {
        return siblingOkapiTikal;
    }
    return 'tikal';
}

function runCommand(cmd: string, cwd: string) {
    console.log(`Executing: ${cmd}`);
    execSync(cmd, { cwd, stdio: 'inherit' });
}

async function main() {
    const rootDir = path.resolve(__dirname, '..');
    const samplesDir = path.join(rootDir, 'samples');
    const tempWorkDir = path.join(rootDir, 'scratch', 'sample_temp');

    if (!fs.existsSync(samplesDir)) {
        console.error(`Samples directory not found at: ${samplesDir}`);
        process.exit(1);
    }

    const tikalCmd = resolveTikalPath(rootDir);
    console.log(`Using Tikal executable: ${tikalCmd}`);

    const targets = [
        { file: 'project_en.docx', srcLang: 'en-US', tgtLang: 'ja-JP', outJson: 'project_en.json' },
        { file: 'project_ja.docx', srcLang: 'ja-JP', tgtLang: 'en-US', outJson: 'project_ja.json' },
        { file: 'project_zh.docx', srcLang: 'zh-CN', tgtLang: 'ja-JP', outJson: 'project_zh.json' }
    ];

    for (const target of targets) {
        const sourceDocx = path.join(samplesDir, target.file);
        if (!fs.existsSync(sourceDocx)) {
            console.warn(`Source sample docx not found: ${sourceDocx}, skipping.`);
            continue;
        }

        console.log(`\n========================================`);
        console.log(`Processing: ${target.file} (${target.srcLang} -> ${target.tgtLang})`);
        console.log(`========================================`);

        // Clean & Re-create temp working dir
        if (fs.existsSync(tempWorkDir)) {
            fs.rmSync(tempWorkDir, { recursive: true, force: true });
        }
        fs.mkdirSync(path.join(tempWorkDir, 'Working', '02_SOURCE'), { recursive: true });
        fs.mkdirSync(path.join(tempWorkDir, 'Working', '03_XLF_JSON'), { recursive: true });

        // 1. Copy sample docx to Working/02_SOURCE
        const copyDest = path.join(tempWorkDir, 'Working', '02_SOURCE', target.file);
        fs.copyFileSync(sourceDocx, copyDest);

        // 2. Run Tikal extraction
        const sourceDir = path.join(tempWorkDir, 'Working', '02_SOURCE');
        const execTikal = `"${tikalCmd}" -x "${target.file}" -sl ${target.srcLang} -tl ${target.tgtLang}`;
        runCommand(execTikal, sourceDir);

        const generatedXlf = path.join(sourceDir, target.file + '.xlf');
        const xlfDest = path.join(tempWorkDir, 'Working', '03_XLF_JSON', target.file + '.xlf');

        if (fs.existsSync(generatedXlf)) {
            fs.renameSync(generatedXlf, xlfDest);
        } else {
            console.error(`XLF was not generated by Tikal for ${target.file}`);
            continue;
        }

        // 3. Parse XLF & run match analysis using official ShWvData service
        const shWvData = new ShWvData();
        shWvData.meta.sourceLang = target.srcLang;
        shWvData.meta.targetLang = target.tgtLang;
        await shWvData.parse([xlfDest]);
        await shWvData.analyze(tempWorkDir);

        const projectJsonData = {
            define: {
                name: "SHWV_DATA",
                version: "1.3"
            },
            meta: {
                bilingualPath: xlfDest,
                files: shWvData.meta.files.length > 0 ? shWvData.meta.files : [{
                    name: target.file + '.xlf',
                    start: 0,
                    end: shWvData.body.units.length > 0 ? shWvData.body.units.length - 1 : 0
                }],
                sourceLang: target.srcLang,
                targetLang: target.tgtLang,
                tmFiles: [],
                tbFiles: []
            },
            body: {
                units: shWvData.body.units
            }
        };

        // Save generated project JSON to samples directory
        const outPath = path.join(samplesDir, target.outJson);
        fs.writeFileSync(outPath, JSON.stringify(projectJsonData, null, 2), 'utf-8');
        console.log(`Successfully generated sample project JSON: ${outPath}`);
    }

    // Cleanup temp dir
    if (fs.existsSync(tempWorkDir)) {
        fs.rmSync(tempWorkDir, { recursive: true, force: true });
    }

    console.log('\nAll sample project JSONs generated successfully!');

    console.log('\nGenerating ZIP packages...');
    const JSZip = require('jszip');
    const allFiles = fs.readdirSync(samplesDir);
    const baseNames = new Set(targets.map(t => t.outJson.replace(/\.json$/, '')));
    
    for (const base of baseNames) {
        const zip = new JSZip();
        let hasFiles = false;
        
        for (const file of allFiles) {
            if (file.startsWith(base + '.') && !file.endsWith('.zip')) {
                const filePath = path.join(samplesDir, file);
                const fileData = fs.readFileSync(filePath);
                zip.file(file, fileData);
                hasFiles = true;
                console.log(`  Added ${file} to ${base}.zip`);
            }
        }
        
        if (hasFiles) {
            const zipPath = path.join(samplesDir, `${base}.zip`);
            const content = await zip.generateAsync({ type: 'nodebuffer' });
            fs.writeFileSync(zipPath, content);
            console.log(`-> Created ${base}.zip`);
        }
    }
}

main().catch(err => {
    console.error('Failed to generate sample projects:', err);
    process.exit(1);
});
